{% set name = "flaky" %}
{% set version = "3.6.0" %}
{% set hash_type = "sha256" %}
{% set hash = "c24e321b3b4b4a2d323b646acff6738e7601849832f4280864d69f00a6a9869d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - flaky

about:
  home: https://github.com/box/flaky
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Plugin for nose or py.test that automatically reruns flaky tests.
  description: |
    Flaky is a plugin for nose or py.test that automatically reruns flaky
    tests.
  dev_url: https://github.com/box/flaky

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - rlaverde
