# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XweIENOuygmDN2AIXACTc4AI5HmzyKpPS3MSffwXQp5/YCY6+ay5icAngLDBtph80fLnzYKpUJr+hlvCWKCZH7EnSf5cp+ioWtjMznwI8ZS3zHZjjgElIOWh57/nPp054owW3qP9UxpUlW48o713vm/kaEjVTpxVs/9YS3uX10kAAovXO9kqztsPAnvwICc9tqhUg8RkqEdKaLewhEXD3Kbhxec46JmsAfYHDqE5BlkBE97pRM1Rg2LOk+GF8JMSAs7ynX3O0JMRpKow1rocmRi7fvzU0Idef+yz32Idc+tFktgqUIrsIsuTC2nPnCZQiZ1LpXSRUPIivf419vaSuCT5prUvOs8hbYi48YM4xcwpe3RO8mF8l3NOwMD/qGOTV7+YAxYYjmdFT8xZIg1PMvv+cVqutvFuJs6r0Krdk+Ks7YCmklJF+Q9N0xyUIw4PsqSU0uSCXHU9Pps1fTBOPYimUWEj5VQGUkd/0zZmb1YeOuz+leaWOHOv1+Fh/D5HIOh2mxUTbcgdAghpebA+alrALuDcLrOSjhOVATbwRlAmIz+kpxALLE3zoUQFKh0LF5uo7R7Icz72ObaKqejwHMSIXiC4tq+tau+Dx9qF46HQ8Fx0BvuFOMBLYCLYLfvpB/3M7LfZxqnOkkbwgo8qZ5Oc5j0f1ZB9pR11Fzn3qq0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
