travis:
  secure:
    BINSTAR_TOKEN: ffMVX14TrTgmIEGUHbyeFIYrGNQ4pRm/qVeLQui1pHI/yLpsNgMexOiaU80hJHWp+cQf1haG9rVFgxT4XSZFZ4TCPFZzZiw9rX0Rfcprw72YWSrSFju/lF5+MgogDTbHn9xqF0ujpSFkO1/35JFE3brZZMBNgoTV4HeiBH0raqWiCX/XVClR0JBtXMHQfwJXnvDrF+eWvMPeZzo1juM8+VD0e8Xmurewn0IymWlhmsfwbm9v68V2eU8mYxOywJd7qD2vcTgS2zY+DnpP/sn6zMpdHM9eiaIgMn6hgW/9CDMUzxoMEvaLSVlFnO025CXGlCfbfYNuQ7lqINpq9JZiHkiZzpdXl8n/Wn12hKBRSj6F6SpsTVIMEx9Z2PibAyHKO4mqftRRayug/lxIu+OKhjjDdCeOpCCkq8qi5pNGHCTbhpC2QRNIQ7su+BoZKIRMDQx6TZbrns7si93Xnky5G0VS39ZKVBjvu+Ciwbkn4/IXMeGImqQYBOiP3kzPNEhL9sEfl+3UT7BANkyju85rFsGvl55VCoYgsODFELXwbPGL5F/7lzYFpnhXypNV00ZLO0khxL9rSYCR3GbMj+C6d4AGU5WCzgdquTZJ4mrgQEu+4Jr/Svg7afkMjnEdqTbMPpV3dMV9r98R5kHgsbIjxd8TjtiloDwwQd25xHObHY8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
