travis:
  secure:
    BINSTAR_TOKEN: QZrNGQ1wpgFhkSfW6ifibBVbqOr4RI/viQ4qK6h0UDrqBIOtSqdKKRoKceBUe55eLFullKnmN3d8Nq4yCENzaqKO1d56cimO7cRBMe7JxmgPF+mLwxeD8NHgWxspzPoRMxvxZPHIZdBdK6/VqVxY0ubWow2x+Rgfod5EedZt45zkwg6SiAq+Q8DJ9n13KL7nJJcoW74H177bOo+9IS0KFEBpDb3tV3CRfG91kemF5En8JVIGeh/aSo/9jCJdVR5TenU4sfimyosM6xk4vNc3BaWTmIkhlz5SHiUF7Y3KIzaFWYLBMWA9u+vqfrTFCl9tQ8zTrrQGc2NWr6DkgPQlEwOv37gssqOMafS94RRHhai+JvBDuJHRhq8DK/if6tx8dC1aSiSB2sLchD8zoaZ0TJik1W2zIWkEtGbuuQreWsQyUbI/sLTHu2HqeWqtjCoVWJ8q+u/0JzeFaKnlBzd0u5WuM6a+NI5ayGGf4i2jvYYWTM3lHcnb89yCn2PbcYVUi/7bE2xevE3y08IpRbxvDH99w+xJv+fFYczdcM8FZ61Bc9AYUoWPJ+D8czCC5ST94mGXiyPmqbfF5i6g4zOudISedmniPkPFegmGG7T1Mz/Fw7Wlb20NkpftROdPM4LJ4ViQiQCH+kWsT70OMcINeYBeWLSUCMCGrTqfhBb+ccA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
